message(STATUS "Configuring: ${MODULE_NAME}")

qt_add_qml_module(
    ${MODULE_NAME}
    URI "${MODULE_NAME}"
    VERSION 1.0
    QML_FILES ${QML_FILE_LIST}
)

list(APPEND QML_IMPORT_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
set(QML_IMPORT_PATH "${QML_IMPORT_PATH}" PARENT_SCOPE)
